In [2]:
import sqlite3
import pandas as pd

In [3]:
# Load CSV into SQLite
conn = sqlite3.connect('sleep.db')
df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
df.to_sql('sleep', conn, index=False, if_exists='replace')

374

In [4]:
pd.read_sql('SELECT * FROM sleep LIMIT 5', conn)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [5]:
pd.read_sql('SELECT Occupation, AVG("Quality of Sleep") AS avg_sleep_quality FROM sleep GROUP BY Occupation', conn)

              Occupation  avg_sleep_quality
0             Accountant           7.891892
1                 Doctor           6.647887
2               Engineer           8.412698
3                 Lawyer           7.893617
4                Manager           7.000000
5                  Nurse           7.369863
6   Sales Representative           4.000000
7            Salesperson           6.000000
8              Scientist           5.000000
9      Software Engineer           6.500000
10               Teacher           6.975000

In [12]:
pd.read_sql('SELECT "Stress Level", Occupation FROM sleep GROUP BY Occupation', conn)

    Stress Level            Occupation
0              6            Accountant
1              8                Doctor
2              3              Engineer
3              5                Lawyer
4              5               Manager
5              7                 Nurse
6              8  Sales Representative
7              7           Salesperson
8              6             Scientist
9              6     Software Engineer
10             7               Teacher

In [14]:
pd.read_sql('SELECT AVG("Sleep Duration"),* FROM sleep GROUP BY Occupation', conn)

,"AVG(""Sleep Duration"")",Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,7.113514,67,Male,32,Accountant,7.2,8,50,6,Normal Weight,118/76,68,7000,None
1,6.970423,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,7.987302,51,Male,32,Engineer,7.5,8,45,3,Normal,120/80,70,8000,None
3,7.410638,94,Male,35,Lawyer,7.4,7,60,5,Obese,135/88,84,3300,Sleep Apnea
4,6.900000,264,Female,45,Manager,6.9,7,55,5,Overweight,125/82,75,5500,None
5,7.063014,17,Female,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000,Sleep Apnea
6,5.900000,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
7,6.403125,178,Male,42,Salesperson,6.5,6,45,7,Overweight,130/85,72,6000,Insomnia
8,6.000000,69,Female,33,Scientist,6.2,6,50,6,Overweight,128/85,76,5500,None
9,6.750000,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
10,6.690000,7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia

In [20]:
pd.read_sql('SELECT "Stress Level", "Quality of Sleep", Occupation FROM sleep GROUP BY Occupation', conn)

    Stress Level  Quality of Sleep            Occupation
0              6                 8            Accountant
1              8                 6                Doctor
2              3                 8              Engineer
3              5                 7                Lawyer
4              5                 7               Manager
5              7                 5                 Nurse
6              8                 4  Sales Representative
7              7                 6           Salesperson
8              6                 6             Scientist
9              6                 6     Software Engineer
10             7                 6               Teacher

In [19]:
pd.read_sql('SELECT "Stress Level", "Quality of Sleep", Occupation FROM sleep WHERE "Stress Level" >= 7 GROUP BY Occupation', conn)

   Stress Level  Quality of Sleep            Occupation
0             7                 7            Accountant
1             8                 6                Doctor
2             7                 5              Engineer
3             7                 5                 Nurse
4             8                 4  Sales Representative
5             7                 6           Salesperson
6             8                 4             Scientist
7             8                 4     Software Engineer
8             7                 6               Teacher

In [21]:
pd.read_sql('SELECT "BMI Category", "Heart Rate" FROM sleep GROUP BY "BMI Category"', conn)

    BMI Category  Heart Rate
0         Normal          75
1  Normal Weight          80
2          Obese          85
3     Overweight          77

In [28]:
pd.read_sql('SELECT Occupation, COUNT(Occupation) AS count_occu FROM sleep GROUP BY Occupation ORDER BY count_occu DESC', conn)

              Occupation  count_occu
0                  Nurse          73
1                 Doctor          71
2               Engineer          63
3                 Lawyer          47
4                Teacher          40
5             Accountant          37
6            Salesperson          32
7      Software Engineer           4
8              Scientist           4
9   Sales Representative           2
10               Manager           1

In [35]:
pd.read_sql('SELECT "Physical Activity Level", "Quality Of Sleep" Occupation FROM sleep GROUP BY Occupation ORDER BY "Physical Activity Level" DESC ', conn)

    Physical Activity Level  Occupation
0                        60           7
1                        60           6
2                        55           7
3                        50           6
4                        50           8
5                        45           6
6                        45           8
7                        42           6
8                        40           6
9                        40           5
10                       30           4